- name: shared-hosts-file
  hosts: all
  gather_facts: false
  become: true
  roles:
    - shared-hosts-file
  tags:
    - shared-hosts-file

- name: influxdb-meta
  hosts: influxdb-meta
  gather_facts: false
  become: true
  serial: 1
  roles:
    - influxdb-meta
  tags:
    - influxdb-meta

- name: influxdb-data
  hosts: influxdb-data
  serial: 1
  gather_facts: false
  become: true
  roles:
    - influxdb-data
  tags:
    - influxdb-data