influxdb_ee_meta_rpm: https://dl.influxdata.com/enterprise/releases/influxdb-meta-1.3.8_c1.3.8.x86_64.rpm
influxdb_ee_data_rpm: https://dl.influxdata.com/enterprise/releases/influxdb-data-1.3.8_c1.3.8.x86_64.rpm

influxdb_ee_auth_enabled: "true"
influxdb_ee_registration_enabled: "false"
influxdb_ee_cache_max_memory_size: 33554432000
influxdb_ee_max_series_per_database: 10000000
influxdb_ee_max_values_per_tag: 0

influxdb_ee_https_enabled: "false"
influxdb_ee_meta_tls_enabled: "false"
influxdb_ee_meta_insecure_tls: "false"

#either inmem or tsi1
influxdb_data_dir: /var/lib/influxdb/data
influxdb_wal_dir: /var/lib/influxdb/wal
influxdb_hh_dir: /var/lib/influxdb/hh
influxdb_index_version: tsi1
influxdb_store_enabled: "false"
influxdb_query_log_enabled: "false"
influxdb_http_request_logging_enabled: "false"
