- name: install tls certificate
  copy: content={{ influxdb_ee_https_certificate_content }} dest={{ influxdb_ee_https_certificate }} owner=root group=influxdb mode=0640
  when:
    - influxdb_ee_https_certificate_content is defined
    - influxdb_ee_https_certificate is defined
  notify: restart influxdb-meta

- name: install influxdb meta
  yum: name={{ influxdb_ee_meta_rpm }}
  notify: restart influxdb-meta

- name: setup influxdb meta config
  template:
    src: influxdb-meta.conf
    dest: /etc/influxdb/influxdb-meta.conf
  notify: restart influxdb-meta

- name: start and enable influxdb-meta
  service: name=influxdb-meta state=started enabled=yes
