- name: install tls certificate
  copy: content={{ influxdb_ee_https_certificate_content }} dest={{ influxdb_ee_https_certificate }} owner=root group=influxdb mode=0640
  when:
    - influxdb_ee_https_certificate_content is defined
    - influxdb_ee_https_certificate is defined
  notify: restart influxdb

- name: install influxdb data
  yum: name={{ influxdb_ee_data_rpm }}
  notify: restart influxdb

- name: setup influxdb data config
  template:
    src: influxdb.conf
    dest: /etc/influxdb/influxdb.conf
  notify: restart influxdb

- name: start and enable influxdb
  service: name=influxdb state=started enabled=yes

- name: make sure influxdb gets restarted before waiting for it to come back up
  meta: flush_handlers

- name: wait for inlfuxdb to come online
  wait_for: host=127.0.0.1 port=8086
